---
title: "Pingüinos de Adelia"
author: "Miriam Lerma"
date: "22/4/2021"
output:
  xaringan::moon_reader:
    seal:false
---
class: title-slide, center, middle, inverse
background-image: url(https://images.unsplash.com/photo-1544817287-d26f7ed1e4d9?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80)
background-size: cover
```{r, eval=FALSE, echo=FALSE}
devtools::install_github("yihui/xaringan")
```

# ¿Son los machos más pesados que las hembras en pingüinos de Adelia?

---
class: center

# Mi tabla
```{r cargar datos, echo=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(datos)
#remotes::install.packages("cienciadedatos/datos")
Pingus<-datos::pinguinos
```

```{r, echo=FALSE}
Peso_sexo_Adelia<-Pingus%>%
  filter(especie=='Adelia')%>%
  group_by(sexo)%>%
  summarise(peso=mean(masa_corporal_g))%>%
  drop_na()
```

```{r, echo=FALSE}
Peso_sexo_Adelia %>% 
  head()%>%
  knitr::kable(format = "html")
```

---

# Mi figura

.center[
```{r, echo=FALSE, fig.height=5, warning=FALSE}
Pingus%>%
  filter(especie=='Adelia')%>%
  ggplot(aes(x = sexo, y = masa_corporal_g)) +
  geom_boxplot(aes(fill = sexo))+
  theme_classic()
```
]

---


